### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by liaohuqiu**
Update README. Add a online Maven repository which contains the components built by this project.

### CODE REVIEW

**Comment by Shusshu** [comment]
Hosting a public repo for google product does not respect the license

**Comment by liaohuqiu** [comment]
Thank your for your reminder, I did not notice that, sorry.

**Comment by mosabua** [comment]
I would suggest to delete the github repo asap. You are violoating the license from github and from Google by hosting these files.

**Comment by liaohuqiu** [comment]
@mosabua DELETED now. THANK YOU.

**Pull request closed without merging**
