### PR TITLE
Add Android N

### PR DESCRIPTION
**Pull request by danielpassos**
I'm trying to make @travis-ci happy, but seems it don't like the too much output we have in the build. 

https://travis-ci.org/danielpassos/maven-android-sdk-deployer/builds/154760643

### CODE REVIEW

**Comment by mosabua** [comment]
Let me check that out in the next days. Sorry for the delay. Busy summer..

**Comment by malachid** [comment]
```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

The build has been terminated.
```

Part of that should be reduced with another build, since there was a lot of repo updates - but perhaps increasing the max log size would be the quickest fix.

Also, if upgrading to support Nougat, we may want to consider changing it to JDK8.  It's been out for a few years and the last update to JDK7 was a year and a half ago.

**Comment by danielpassos** [comment]
@malachid I think increase the max log size is not possible yet (https://github.com/travis-ci/travis-ci/issues/3865). Am I wrong?

**Comment by malachid** [comment]
A feature request from over a year ago. I wonder why the delay in updating the size.

**Comment by malachid** [comment]
Can we try kicking off the build again since many of those downloads should not be necessary a second time?

**Comment by danielpassos** [comment]
@malachid I think only the owner of the repo can do this, anyway I think it will not fix the problem. I only have green build using `--quiet` 

See: https://travis-ci.org/danielpassos/maven-android-sdk-deployer/builds/159689694

**Comment by mosabua** [comment]
Finally got to merge this ... lets see what it does in master. Locally all is fine..

**Comment by mosabua** [comment]
Add ons were missing but I added them in master

**Pull request merged**
