### PR TITLE
SDK update

### PR DESCRIPTION
**Pull request by eddabjork**
Update for Android 7.1 with API level 25.
Also; noticed an error in platforms/android-24/pom.xml

### CODE REVIEW

**Comment by danielpassos** [comment]
Hi @eddabjork,

I'm about to send it for a long time see => https://github.com/simpligility/maven-android-sdk-deployer/compare/master...danielpassos:Android-N

But I'm waiting Google release the Google APIs SDK :(

**Comment by eddabjork** [comment]
@danielpassos ah ok, yes I noticed there was no Google APIs SDK for API level 25. That's why I just added the platform but not add-ons. But I guess we need to wait for Google then :/

**Comment by danielpassos** [comment]
@eddabjork Nice job anyway 👍

**Comment by eddabjork** [comment]
@danielpassos thank you! :)

**Comment by Shusshu** [comment]
@eddabjork Add a changelog line ?

**Comment by eddabjork** [comment]
@Shusshu yes sure, you want me to create a new PR for that? Maybe it's easier if you just add it:

- Edda Björk Konráðsdóttir, Android 7.1 API 25

**Pull request merged**
